// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWouAchpzp6tdy39Ifz3obPU0t3S3AL4',
    appId: '1:1024763999484:web:e89b07946c20ee2b81d379',
    messagingSenderId: '1024763999484',
    projectId: 'chatylife-b2e05',
    authDomain: 'chatylife-b2e05.firebaseapp.com',
    storageBucket: 'chatylife-b2e05.firebasestorage.app',
    measurementId: 'G-RZKWZ061L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvxNH0LUz8W85R7pOXbk-V0cyPxCBJZC4',
    appId: '1:1024763999484:android:e8257610f635f7d081d379',
    messagingSenderId: '1024763999484',
    projectId: 'chatylife-b2e05',
    storageBucket: 'chatylife-b2e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBy5tU1Zt3lWQveHjDkYcK-M5L4MEatpg',
    appId: '1:1024763999484:ios:f14a882dda9205cf81d379',
    messagingSenderId: '1024763999484',
    projectId: 'chatylife-b2e05',
    storageBucket: 'chatylife-b2e05.firebasestorage.app',
    iosBundleId: 'com.example.chatyLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBy5tU1Zt3lWQveHjDkYcK-M5L4MEatpg',
    appId: '1:1024763999484:ios:f14a882dda9205cf81d379',
    messagingSenderId: '1024763999484',
    projectId: 'chatylife-b2e05',
    storageBucket: 'chatylife-b2e05.firebasestorage.app',
    iosBundleId: 'com.example.chatyLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWouAchpzp6tdy39Ifz3obPU0t3S3AL4',
    appId: '1:1024763999484:web:eab85b20afa8fc8581d379',
    messagingSenderId: '1024763999484',
    projectId: 'chatylife-b2e05',
    authDomain: 'chatylife-b2e05.firebaseapp.com',
    storageBucket: 'chatylife-b2e05.firebasestorage.app',
    measurementId: 'G-KEPNZCPS9S',
  );

}